export const EXAMS = [
  {
    id: "exani1",
    name: "EXANI-I",
    short: "Bachillerato",
    fullName: "Examen Nacional de Ingreso al Bachillerato",
    color: "#7A5FA5",
    tint: "#EDE8F5",
    description: "Para ingresar al bachillerato. Evalúa habilidades matemáticas, verbales, analíticas y comprensión lectora.",
    areas: [
      { id: "imat",  name: "Habilidades Matemáticas", questions: 30 },
      { id: "iana",  name: "Pensamiento Analítico",   questions: 30 },
      { id: "ilec",  name: "Comprensión Lectora",     questions: 30 },
      { id: "iverb", name: "Habilidades Verbales",    questions: 30 },
    ],
  },
  {
    id: "exani2",
    name: "EXANI-II",
    short: "Licenciatura",
    fullName: "Examen Nacional de Ingreso a la Licenciatura",
    color: "#6B7C45",
    tint: "#EBF0DC",
    description: "Para ingresar a la licenciatura. Evalúa habilidades básicas de pensamiento y conocimientos de bachillerato.",
    areas: [
      { id: "mat",  name: "Pensamiento Matemático", questions: 30 },
      { id: "ana",  name: "Pensamiento Analítico",  questions: 30 },
      { id: "lec",  name: "Comprensión Lectora",    questions: 30 },
      { id: "red",  name: "Redacción Indirecta",    questions: 30 },
    ],
  },
  {
    id: "exani3",
    name: "EXANI-III",
    short: "Posgrado",
    fullName: "Examen Nacional de Ingreso al Posgrado",
    color: "#5B6FA0",
    tint: "#E8ECFA",
    description: "Para ingresar a especialidad, maestría o doctorado. Evalúa habilidades intelectuales avanzadas.",
    areas: [
      { id: "verb", name: "Habilidad Verbal",               questions: 30 },
      { id: "hmat", name: "Habilidad Matemática",           questions: 30 },
      { id: "leca", name: "Comprensión Lectora Avanzada",   questions: 30 },
      { id: "ing",  name: "Inglés Técnico",                 questions: 30 },
    ],
  },
  {
    id: "egel",
    name: "EGEL",
    short: "Egreso",
    fullName: "Examen General para el Egreso de la Licenciatura",
    color: "#A6643C",
    tint: "#F5EDE4",
    description: "Para egresados de licenciatura. Certifica los conocimientos y habilidades del área disciplinar.",
    areas: [
      { id: "disc", name: "Área Disciplinar",  questions: 40 },
      { id: "etic", name: "Ética Profesional", questions: 20 },
      { id: "com",  name: "Comunicación",      questions: 20 },
    ],
  },
];
