export const EXAMS = [
  {
    id: "exani1",
    name: "EXANI-I",
    short: "Bachillerato",
    fullName: "Examen Nacional de Ingreso al Bachillerato",
    color: "#7A5FA5",
    tint: "#EDE8F5",
    description: "Para ingresar al bachillerato. Evalua habilidades matematicas, verbales, analiticas y comprension lectora.",
    areas: [
      { id: "imat",  name: "Habilidades Matematicas",  questions: 30 },
      { id: "iana",  name: "Pensamiento Analitico",    questions: 30 },
      { id: "ilec",  name: "Comprension Lectora",      questions: 30 },
      { id: "iverb", name: "Habilidades Verbales",     questions: 30 },
    ],
  },
  {
    id: "exani2",
    name: "EXANI-II",
    short: "Licenciatura",
    fullName: "Examen Nacional de Ingreso a la Licenciatura",
    color: "#6B7C45",
    tint: "#EBF0DC",
    description: "Para ingresar a la licenciatura. Evalua habilidades basicas de pensamiento y conocimientos de bachillerato.",
    areas: [
      { id: "mat",  name: "Pensamiento Matematico",  questions: 30 },
      { id: "ana",  name: "Pensamiento Analitico",   questions: 30 },
      { id: "lec",  name: "Comprension Lectora",     questions: 30 },
      { id: "red",  name: "Redaccion Indirecta",     questions: 30 },
    ],
  },
  {
    id: "exani3",
    name: "EXANI-III",
    short: "Posgrado",
    fullName: "Examen Nacional de Ingreso al Posgrado",
    color: "#5B6FA0",
    tint: "#E8ECFA",
    description: "Para ingresar a especialidad, maestria o doctorado. Evalua habilidades intelectuales avanzadas.",
    areas: [
      { id: "verb", name: "Habilidad Verbal",                questions: 30 },
      { id: "hmat", name: "Habilidad Matematica",            questions: 30 },
      { id: "leca", name: "Comprension Lectora Avanzada",    questions: 30 },
      { id: "ing",  name: "Ingles Tecnico",                  questions: 30 },
    ],
  },
  {
    id: "egel",
    name: "EGEL",
    short: "Egreso",
    fullName: "Examen General para el Egreso de la Licenciatura",
    color: "#A6643C",
    tint: "#F5EDE4",
    description: "Para egresados de licenciatura. Certifica los conocimientos y habilidades del area disciplinar.",
    areas: [
      { id: "disc", name: "Area Disciplinar",    questions: 40 },
      { id: "etic", name: "Etica Profesional",   questions: 20 },
      { id: "com",  name: "Comunicacion",        questions: 20 },
    ],
  },
];
